/* PNW Wildflower Quiz — species data
   Photos: Wikimedia Commons (see credits.json for photographer & license). */
const FLOWERS = [
  { id: "western-trillium", common: "Western Trillium", scientific: "Trillium ovatum", family: "Bunchflower family", color: "white" },
  { id: "pacific-bleeding-heart", common: "Pacific Bleeding Heart", scientific: "Dicentra formosa", family: "Poppy family", color: "pink" },
  { id: "common-camas", common: "Common Camas", scientific: "Camassia quamash", family: "Asparagus family", color: "purple" },
  { id: "common-red-paintbrush", common: "Common Red Paintbrush", scientific: "Castilleja miniata", family: "Broomrape family", color: "red" },
  { id: "tall-oregon-grape", common: "Tall Oregon Grape", scientific: "Mahonia aquifolium", family: "Barberry family", color: "yellow" },
  { id: "salmonberry", common: "Salmonberry", scientific: "Rubus spectabilis", family: "Rose family", color: "pink" },
  { id: "red-columbine", common: "Red Columbine", scientific: "Aquilegia formosa", family: "Buttercup family", color: "red" },
  { id: "fireweed", common: "Fireweed", scientific: "Chamaenerion angustifolium", family: "Evening-primrose family", color: "pink" },
  { id: "pacific-rhododendron", common: "Pacific Rhododendron", scientific: "Rhododendron macrophyllum", family: "Heath family", color: "pink" },
  { id: "skunk-cabbage", common: "Skunk Cabbage", scientific: "Lysichiton americanus", family: "Arum family", color: "yellow" },
  { id: "chocolate-lily", common: "Chocolate Lily", scientific: "Fritillaria affinis", family: "Lily family", color: "maroon" },
  { id: "tiger-lily", common: "Tiger Lily", scientific: "Lilium columbianum", family: "Lily family", color: "orange" },
  { id: "avalanche-lily", common: "Avalanche Lily", scientific: "Erythronium montanum", family: "Lily family", color: "white" },
  { id: "glacier-lily", common: "Glacier Lily", scientific: "Erythronium grandiflorum", family: "Lily family", color: "yellow" },
  { id: "beargrass", common: "Beargrass", scientific: "Xerophyllum tenax", family: "Bunchflower family", color: "white" },
  { id: "broadleaf-lupine", common: "Broadleaf Lupine", scientific: "Lupinus latifolius", family: "Pea family", color: "purple" },
  { id: "nootka-rose", common: "Nootka Rose", scientific: "Rosa nutkana", family: "Rose family", color: "pink" },
  { id: "oxeye-daisy", common: "Oxeye Daisy", scientific: "Leucanthemum vulgare", family: "Aster family", color: "white" },
  { id: "cow-parsnip", common: "Cow Parsnip", scientific: "Heracleum maximum", family: "Carrot family", color: "white" },
  { id: "foxglove", common: "Foxglove", scientific: "Digitalis purpurea", family: "Plantain family", color: "purple" },
  { id: "yarrow", common: "Yarrow", scientific: "Achillea millefolium", family: "Aster family", color: "white" },
  { id: "pearly-everlasting", common: "Pearly Everlasting", scientific: "Anaphalis margaritacea", family: "Aster family", color: "white" },
  { id: "broadleaf-stonecrop", common: "Broadleaf Stonecrop", scientific: "Sedum spathulifolium", family: "Stonecrop family", color: "yellow" },
  { id: "western-buttercup", common: "Western Buttercup", scientific: "Ranunculus occidentalis", family: "Buttercup family", color: "yellow" },
  { id: "shooting-star", common: "Few-flowered Shooting Star", scientific: "Primula pauciflora", family: "Primrose family", color: "pink" },
  { id: "stream-violet", common: "Stream Violet", scientific: "Viola glabella", family: "Violet family", color: "yellow" },
  { id: "salal", common: "Salal", scientific: "Gaultheria shallon", family: "Heath family", color: "white" },
  { id: "twinflower", common: "Twinflower", scientific: "Linnaea borealis", family: "Honeysuckle family", color: "pink" },
  { id: "bunchberry", common: "Bunchberry", scientific: "Cornus canadensis", family: "Dogwood family", color: "white" },
  { id: "pacific-dogwood", common: "Pacific Dogwood", scientific: "Cornus nuttallii", family: "Dogwood family", color: "white" },
  { id: "wild-ginger", common: "Wild Ginger", scientific: "Asarum caudatum", family: "Birthwort family", color: "maroon" },
  { id: "false-solomons-seal", common: "False Solomon's Seal", scientific: "Maianthemum racemosum", family: "Asparagus family", color: "white" },
  { id: "indian-pipe", common: "Indian Pipe", scientific: "Monotropa uniflora", family: "Heath family", color: "white" },
  { id: "harvest-brodiaea", common: "Harvest Brodiaea", scientific: "Brodiaea coronaria", family: "Asparagus family", color: "purple" },
  { id: "leafy-aster", common: "Leafy Aster", scientific: "Symphyotrichum foliaceum", family: "Aster family", color: "purple" },
  { id: "scarlet-gilia", common: "Scarlet Gilia", scientific: "Ipomopsis aggregata", family: "Phlox family", color: "red" },
  { id: "sea-thrift", common: "Sea Thrift", scientific: "Armeria maritima", family: "Leadwort family", color: "pink" },
  { id: "coastal-strawberry", common: "Coastal Strawberry", scientific: "Fragaria chiloensis", family: "Rose family", color: "white" },
  { id: "cascade-penstemon", common: "Cascade Penstemon", scientific: "Penstemon serrulatus", family: "Plantain family", color: "purple" },
  { id: "oregon-iris", common: "Oregon Iris", scientific: "Iris tenax", family: "Iris family", color: "purple" },
  { id: "candy-flower", common: "Candy Flower", scientific: "Claytonia sibirica", family: "Miner's lettuce family", color: "pink" },
  { id: "menzies-larkspur", common: "Menzies' Larkspur", scientific: "Delphinium menziesii", family: "Buttercup family", color: "purple" },
  { id: "self-heal", common: "Self-heal", scientific: "Prunella vulgaris", family: "Mint family", color: "purple" },
  { id: "woolly-sunflower", common: "Woolly Sunflower", scientific: "Eriophyllum lanatum", family: "Aster family", color: "yellow" },
  { id: "blue-eyed-grass", common: "Blue-eyed Grass", scientific: "Sisyrinchium bellum", family: "Iris family", color: "purple" },
  { id: "western-wallflower", common: "Western Wallflower", scientific: "Erysimum capitatum", family: "Mustard family", color: "orange" },
];

FLOWERS.forEach(f => { f.image = `images/${f.id}.jpg`; });
